-- Canon AI — plain-Postgres schema mirror, DERIVED FROM supabase/migrations/.
--
-- THE MIGRATION CHAIN IS AUTHORITATIVE. This file is regenerated by the
-- schema lane so a fresh plain-Postgres database built from it matches one
-- built from the full chain (tables, columns — including column order —
-- constraints, and indexes). Do not hand-edit table shapes here without a
-- migration; see docs/workstreams.md (migration lane).
--
-- Derived from, in order:
--   20260703033004_canon_schema.sql
--   20260703050000_coverage_notes.sql
--   20260703060000_identity_and_access.sql
--   20260703090000_report_engine_hardening.sql
--   20260703100000_queued_ddl_and_attribution.sql
--
-- Supabase-only pieces are summarized in comments instead of DDL, because
-- plain Postgres has no `auth` schema or auth.uid():
--   * FKs into auth.users (profiles.user_id, worlds.owner_id, world_members.
--     user_id) are plain uuid columns here — the FKs exist in the migrations.
--   * RLS policies and the canon_* SECURITY DEFINER helper functions live only
--     in the migrations; see the RLS summary at the end of this file.
--
-- Apply on plain Postgres: psql ... -f db/schema.sql
-- Requires: btree_gist (exclusion constraints mixing = with &&)

create extension if not exists btree_gist;
create extension if not exists pgcrypto;
-- create extension if not exists vector;  -- pgvector: deferred until Audience Memory (P2)

-- ---------- enums ----------
create type entity_kind as enum ('character','location','object','faction','event','rule','other');
create type assertion_status as enum ('draft','canon','sealed','retconned','rejected');
create type alias_kind as enum ('name_variant','nickname','role_reference');

-- ---------- worlds (one writer's show/book/series) ----------
create table worlds (
  id          bigint generated always as identity primary key,
  name        text not null,
  created_at  timestamptz not null default now(),
  owner_id    uuid                       -- auth.users.id; FK (on delete set null)
                                         -- in the identity migration. Nullable:
                                         -- pipeline-loaded worlds have no owner yet.
);

-- ---------- works & scenes (provenance spine) ----------
create table works (                       -- an episode, chapter, or document
  id          bigint generated always as identity primary key,
  world_id    bigint not null references worlds(id) on delete cascade,
  title       text not null,               -- 'S1E01', 'Manuscript ch. 4', 'World doc'
  source_file text,
  sort_order  int not null
);

create table scenes (
  id             bigint generated always as identity primary key,
  work_id        bigint not null references works(id) on delete cascade,
  slug           text,                     -- 'INT. BOATHOUSE — NIGHT'
  story_position int not null,             -- global integer axis per world (v0; see D6)
  is_flashback   boolean not null default false,
  raw_text       text not null,
  unique (work_id, story_position)
);
create index scenes_story_pos on scenes (story_position);

-- ---------- entities & aliases ----------
create table entities (
  id        bigint generated always as identity primary key,
  world_id  bigint not null references worlds(id) on delete cascade,
  kind      entity_kind not null,
  name      text not null,                 -- canonical
  dossier   text,                          -- short LLM-maintained summary for disambiguation
  provisional boolean not null default false,
  unique (world_id, name, kind)
);

create table aliases (
  entity_id bigint not null references entities(id) on delete cascade,
  alias     text not null,
  kind      alias_kind not null,
  primary key (entity_id, alias)
);
create index aliases_alias on aliases (lower(alias));

-- ---------- assertions: the atomic unit ----------
-- (subject) —predicate→ (object) valid over [story positions), cited, statused.
create table assertions (
  id              bigint generated always as identity primary key,
  world_id        bigint not null references worlds(id) on delete cascade,
  subject_id      bigint not null references entities(id),
  predicate       text not null,           -- closed vocabulary; see docs/extraction.md
  object_id       bigint references entities(id),          -- entity-valued objects
  object_value    text,                                     -- literal/fact-valued objects
  object_assertion_id bigint references assertions(id),     -- epistemic: knows/believes THIS assertion
  polarity        boolean not null default true,            -- false = explicit negation ('cannot drive')
  valid_during    int4range not null,       -- story-position validity; unbounded ends allowed
  established_in_scene bigint not null references scenes(id),
  supporting_quote text,
  confidence      real not null check (confidence >= 0 and confidence <= 1),
  status          assertion_status not null default 'draft',
  confirmed_by_human boolean not null default false,
  superseded_by   bigint references assertions(id),         -- retcon chain (recorded, not reasoned)
  created_at      timestamptz not null default now(),
  confirmed_by    uuid,                     -- auth.users.id of the confirm-queue ruler
                                            -- (canon/rejected); null = pipeline/gate.
                                            -- No FK: rulings survive user deletion.
  confirmed_at    timestamptz,              -- when the confirm-queue ruling landed
  check (object_id is not null or object_value is not null or object_assertion_id is not null)
);
create index assertions_subj   on assertions (subject_id, predicate);
create index assertions_valid  on assertions using gist (valid_during);
create index assertions_status on assertions (world_id, status);
create index assertions_world_valid on assertions using gist (world_id, valid_during);
create index assertions_world_subject_predicate on assertions (world_id, subject_id, predicate);
create index assertions_world_object on assertions (world_id, object_id) where object_id is not null;

-- ---------- write-time continuity invariants (exclusion constraints) ----------
-- A continuity rule as schema: one character cannot be located_at two places
-- over overlapping story intervals. Enforced via a thin typed table that mirrors
-- located_at assertions (kept in sync by the ingest layer).
create table character_locations (
  assertion_id bigint primary key references assertions(id) on delete cascade,
  character_id bigint not null references entities(id),
  location_id  bigint not null references entities(id),
  valid_during int4range not null,
  constraint character_locations_no_overlap
  exclude using gist (
    character_id with =,
    valid_during with &&
  )
);
-- Same pattern available for alive-intervals if death/resurrection churn appears:
-- exclude using gist (character_id with =, valid_during with &&) on a character_lifespans table.

-- ---------- scene presence (high-volume, so typed, not generic assertions) ----------
create table scene_presence (
  scene_id  bigint not null references scenes(id) on delete cascade,
  entity_id bigint not null references entities(id),
  primary key (scene_id, entity_id)
);
create index scene_presence_entity_scene on scene_presence (entity_id, scene_id);

-- ---------- per-world deterministic check / note family toggles ----------
-- Absence means enabled. Disabled rows suppress matching db/checks.sql checks
-- and Reader's Report F1-F4 note families without mutating existing rows.
create table world_family_config (
  world_id    bigint not null references worlds(id) on delete cascade,
  family      text not null,
  enabled     boolean not null default true,
  updated_at  timestamptz not null default now(),
  primary key (world_id, family),
  check (family ~ '^[A-Za-z0-9_]+$')
);
create index world_family_config_disabled
  on world_family_config (world_id, family)
  where not enabled;

-- ---------- check findings (output of db/checks.sql runs) ----------
create table findings (
  id          bigint generated always as identity primary key,
  world_id    bigint not null references worlds(id) on delete cascade,
  check_name  text not null,
  severity    text not null check (severity in ('critical','warning','note')),
  explanation text not null,
  scene_id    bigint references scenes(id),
  assertion_a bigint references assertions(id),
  assertion_b bigint references assertions(id),
  sealed      boolean not null default false,   -- writer marked intentional
  run_at      timestamptz not null default now()
);
create index findings_world_check on findings (world_id, check_name, sealed);

-- ---------- seals: permanent 'intentional' marks, independent of finding runs ----------
create table seals (
  world_id    bigint not null references worlds(id) on delete cascade,
  check_name  text not null,
  assertion_a bigint not null references assertions(id),
  assertion_b bigint references assertions(id),
  reason      text,
  created_at  timestamptz not null default now(),
  coalesce_b  bigint generated always as (coalesce(assertion_b, 0)) stored,
  ruled_by    uuid,                        -- attribution; no FK, outlives the account
  ruled_at    timestamptz,
  primary key (world_id, check_name, assertion_a, coalesce_b)
);

-- ---------- coverage notes (Reader's Report F1-F4 lifecycle) ----------
create table coverage_notes (
  id              uuid primary key default gen_random_uuid(),
  world_id        bigint not null references worlds(id) on delete cascade,
  note_key        text not null unique,
  family          text not null check (family in ('F1','F2','F3','F4')),
  summary         text not null,
  body            text not null,
  evidence        jsonb not null default '{}'::jsonb,
  salience        int not null default 0,
  status          text not null default 'open'
                  check (status in ('open','sealed','dismissed','addressed')),
  first_seen_run  uuid not null,
  last_seen_run   uuid not null,
  resolved_at     timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  status_changed_by uuid,                  -- attribution; no FK, outlives the account
  status_changed_at timestamptz
);
create index coverage_notes_world_status_family
  on coverage_notes (world_id, status, family);
create index coverage_notes_evidence_gin
  on coverage_notes using gin (evidence);

-- ---------- identity: profiles & membership (P3-IDENTITY) ----------
-- One profile row per Supabase auth user (email and Google sign-ins both land
-- in auth.users; we never mint identities ourselves).
create table profiles (
  user_id      uuid primary key,           -- FK auth.users(id) on delete cascade
                                           -- in the identity migration
  display_name text,
  created_at   timestamptz not null default now()
);

create table world_members (
  world_id   bigint not null references worlds(id) on delete cascade,
  user_id    uuid   not null,              -- FK auth.users(id) on delete cascade
                                           -- in the identity migration
  role       text   not null check (role in ('owner','editor','viewer')),
  invited_by uuid,                              -- attribution only; no FK so rows
                                                -- survive inviter account deletion
  created_at timestamptz not null default now(),
  primary key (world_id, user_id)               -- satisfies unique(world_id, user_id)
);
create index world_members_user on world_members (user_id);  -- "my worlds" lookups

-- ---------- sharing (P3-ARTIFACTS) and usage metering (P3-OPS) ----------
create table share_links (
  id         uuid primary key default gen_random_uuid(),
  token      text not null unique,
  world_id   bigint not null references worlds(id) on delete cascade,
  kind       text not null check (kind in ('report','bible')),
  created_by uuid,
  created_at timestamptz not null default now(),
  revoked_at timestamptz                         -- null = live
);

create table usage_events (
  id         bigserial primary key,
  user_id    uuid,
  world_id   bigint references worlds(id) on delete set null,
  kind       text,
  tokens_in  int not null default 0,
  tokens_out int not null default 0,
  cost_usd   numeric(10,4) not null default 0,
  created_at timestamptz not null default now()
);
create index usage_events_user_time on usage_events (user_id, created_at);

-- ---------- billing (P3-BILLING) ----------
-- One Stripe customer per account. Plain uuid, no FK to auth.users: billing
-- history must survive user deletion. Written by billing/webhooks.py under the
-- service role; tier resolution = billing/store.py resolve_tier.
create table billing_customers (
  user_id            uuid primary key,
  stripe_customer_id text unique not null,
  created_at         timestamptz not null default now()
);

-- One live subscription per account; upserts keep the latest Stripe state.
-- current_period_end is null right after checkout.session.completed;
-- customer.subscription.updated fills it (resolve_tier treats null-on-active as paid).
create table billing_subscriptions (
  user_id                uuid primary key,
  stripe_subscription_id text unique not null,
  status                 text not null,
  tier                   text not null default 'free' check (tier in ('free', 'paid')),
  current_period_end     timestamptz,
  updated_at             timestamptz not null default now()
);

-- ---------- world rules (P3-RULES) ----------
-- Per-world structured rules: cannot / only / exception, compiled at read time
-- by canon/rules.py. Never free text beyond label. disabled_at set = rule off.
create table world_rules (
  id          uuid primary key default gen_random_uuid(),
  world_id    bigint not null references worlds(id) on delete cascade,
  kind        text not null check (kind in ('cannot','only','exception')),
  params      jsonb not null,
  label       text,
  created_by  uuid,                        -- no FK: rules survive user deletion
  created_at  timestamptz not null default now(),
  disabled_at timestamptz
);
create index world_rules_world on world_rules (world_id, kind);

-- ---------- pipeline runs (P3-FRONTDOOR) ----------
-- One row per background ingest ("ingest theater"): live phase / progress
-- counters plus the resume state (cumulative candidate extractions as jsonb)
-- when a run fails partway. Server-only writes; clients poll read-only.
create table pipeline_runs (
  id           uuid primary key default gen_random_uuid(),
  world_id     bigint not null references worlds(id) on delete cascade,
  user_id      uuid,                    -- who started it; no FK (survives user deletion)
  status       text not null default 'running'
               check (status in ('running','done','failed','aborted')),
  phase        text not null default 'reading'
               check (phase in ('reading','extracting','resolving','checking','reporting','done')),
  scenes_total int default 0,
  scenes_done  int default 0,
  facts_total  int default 0,
  cost_usd     numeric(10,4) default 0,
  error        text,                    -- last failure message (resumable runs)
  candidates   jsonb,                   -- cumulative scene extractions = the resume state
  created_at   timestamptz default now(),
  heartbeat_at timestamptz default now()  -- runner liveness; stale (>90s) running = failed
);
create index pipeline_runs_world_time on pipeline_runs (world_id, created_at desc);

-- Append-only narration ledger the theater page replays from seq 0 on reload.
create table pipeline_run_events (
  run_id     uuid references pipeline_runs(id) on delete cascade,
  seq        int,
  kind       text not null,             -- scene | entity | finding | phase | stat | error | cost_abort | done
  data       jsonb not null default '{}',
  created_at timestamptz default now(),
  primary key (run_id, seq)
);

-- ---------- RLS summary (Supabase only — full DDL in the migrations) ----------
-- 20260703060000_identity_and_access.sql enables RLS on every table above it
-- (fail closed) and defines canon_role_rank/canon_world_role/canon_has_role +
-- per-parent world resolvers (SECURITY DEFINER), with policies:
--   * profiles: self select/insert/update.
--   * worlds: member select; authenticated insert as owner; owner-only update.
--   * world_members: member select; owner insert/update/delete.
--   * world-scoped content (works, entities, assertions, findings, seals,
--     coverage_notes, scenes, aliases, scene_presence, character_locations):
--     member select, editor insert/update (+ editor delete on seals).
--   * share_links: member select, owner insert/update/delete.
--   * usage_events: own-or-member select; editor insert as self.
-- 20260703100000_queued_ddl_and_attribution.sql adds:
--   * billing_customers / billing_subscriptions: RLS enabled, self select
--     ONLY — no write policies on purpose (writes come via service_role).
--   * world_rules: member select, editor insert/update/delete.
-- world_family_config (20260703090000) is NOT RLS-enabled in the chain: it was
-- created after the identity migration's blanket enable and is written only by
-- the service role / direct-URL pipeline.
-- 20260703110000_pipeline_runs.sql adds:
--   * pipeline_runs / pipeline_run_events: RLS enabled, member select ONLY
--     (canon_has_role via world_id / canon_run_world) — no write policies on
--     purpose; the runner writes via the service role / direct URL.
